"""Public domain vocabulary; this package deliberately has no Qt dependency."""

from seedlink.domain.issues import ISSUE_LEVEL_BY_CODE, Issue, IssueCode, IssueLevel
from seedlink.domain.measures import Measure, MeasureStatus
from seedlink.domain.identity import PersonMatchingResult, match_participants
from seedlink.domain.models import (
    AcceptedLink,
    Activity,
    Client,
    DecisionAction,
    DecisionTarget,
    LeadRef,
    ManualDecision,
    Participant,
    ParticipantLink,
    ParticipantLinkSubject,
    PersonMatchMethod,
    ProductLine,
    ReportResult,
    Survey,
    Voucher,
    VoucherMatchEvidence,
    VoucherMatchMethod,
    VoucherMention,
)
from seedlink.domain.provenance import (
    InputRole,
    InputSnapshot,
    InputSource,
    SourceCell,
    SourceRecord,
)
from seedlink.domain.salesforce_ids import salesforce_id_18, salesforce_id_key
from seedlink.domain.voucher_matching import (
    VoucherMatchingResult,
    VoucherNumberKind,
    VoucherNumberParts,
    match_vouchers,
    parse_voucher_number,
)

__all__ = [
    "AcceptedLink",
    "Activity",
    "Client",
    "DecisionAction",
    "DecisionTarget",
    "InputRole",
    "InputSnapshot",
    "InputSource",
    "ISSUE_LEVEL_BY_CODE",
    "Issue",
    "IssueCode",
    "IssueLevel",
    "LeadRef",
    "ManualDecision",
    "Measure",
    "MeasureStatus",
    "Participant",
    "ParticipantLink",
    "ParticipantLinkSubject",
    "PersonMatchMethod",
    "PersonMatchingResult",
    "ProductLine",
    "ReportResult",
    "SourceCell",
    "SourceRecord",
    "Survey",
    "Voucher",
    "VoucherMatchingResult",
    "VoucherMatchEvidence",
    "VoucherMatchMethod",
    "VoucherMention",
    "VoucherNumberKind",
    "VoucherNumberParts",
    "match_participants",
    "match_vouchers",
    "parse_voucher_number",
    "salesforce_id_18",
    "salesforce_id_key",
]
